spring.application.name=transaction-statistics-api

estatistica.intervalo-padrao-segundos=60

logging.level.com.lucas.transactionstatistics=INFO

management.endpoints.web.exposure.include=health,metrics